data:
    dataset: 'Drone_flight' # название .py скрипта для обработки датасета

    labels: datasets/drone_flight/predictions # путь к папке с аннотациями
    root: datasets/drone_flight/images # путь к папке с изображениями
    
    gaussian_label: # сглаживание меток
        enable: false

    cache_in_memory: false # кэширование данных в памяти
    preprocessing:
        resize: [480, 640] # привести изображения к размеру 640х480
    augmentation: # аугментация данных
        photometric: # фотометрическая аугментация
            enable: false
        homographic: # гомографическая аугментация
            enable: false
    warped_pair: # параметры искаженной пары изображения
        enable: true
        params:
            translation: true # сдвиг
            rotation: true # вращение
            scaling: true # изменение масштаба
            perspective: true # перспективное искажение
            scaling_amplitude: 0.1 # амплитуда масштабирования
            perspective_amplitude_x: 0.1 # амплитуда перспективного искажения по оси X
            perspective_amplitude_y: 0.1 # амплитуда перспективного искажения по оси Y
            patch_ratio: 0.85 # cоотношение размера патча к размеру изображения
            max_angle: 0.52 # максимальный угол вращения
            allow_artifacts: true # обработка артефактов
        valid_border_margin: 3 # полоса допустимого поля по краям изображения

front_end_model: 'Train_model_heatmap' # название модели для фронтальной части сети
training:
    workers_train: 4 # количество рабочих потоков, используемых для тренировки
    workers_val: 2 # количество рабочих потоков, используемых для валидации

model:
    name: 'SuperPointNet_gauss2' # название модели для обучения
    params: {
    }
    detector_loss: # параметры для функции потерь детектора
        loss_type: 'softmax' # тип функции потерь

    batch_size: 8 # размер минибатча для тренировки
    eval_batch_size: 8 # размер минибатча для валидации
    learning_rate: 0.0001 # коэффицент обновления весов
    detection_threshold: 0.015 # порог для определения ключевых точек
    lambda_loss: 1 # параметр, регулирующий вес функции потерь
    nms: 4 # параметр, определяющий размер окна для не максимального подавления
    dense_loss: # параметры плотной функции потерь
        enable: false
        params:
            descriptor_dist: 4 # расстояние для дескрипторов
            lambda_d: 800 # параметр, регулирующий вес плотной функции потерь
    sparse_loss: # параметры для разреженной функции потерь
        enable: true
        params:
            num_matching_attempts: 1000 # количество попыток сопоставления
            num_masked_non_matches_per_match: 100 # количество несоответствий для каждого совпадения
            lamda_d: 1 # параметр, регулирующий вес плотной функции потерь    
            dist: 'cos' # метрика расстояния, используемая для сопоставления
            method: '2d' # метод
    other_settings: 'train 2d, gauss 0.2' # другие настройки

retrain: True # повторное обучение модели
reset_iter: True # сбрасывать ли итерации при дообучении
train_iter: 200000 # количество итераций для тренировки
validation_interval: 2000 # интервал в итерациях, через который будет проводиться валидация
tensorboard_interval: 200 # интервал в итерациях, через который будет записываться информация для TensorBoard
save_interval: 2000 # интервал в итерациях, через который будет сохраняться модель
validation_size: 5 # размер валидационной выборки

pretrained: logs/superpoint_coco_heat2_0/checkpoints/superPointNet_170000_checkpoint.pth.tar  # путь до предварительно обученной модели
